version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  websocket:
    platform: linux/x86_64
    container_name: websocket
    build:
      context: ./apis/websocket
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    volumes:
      - ./apis/websocket:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start
    depends_on:
      - kafka
    restart: always

  # autopay:
  #   platform: linux/amd64
  #   container_name: autopay
  #   build:
  #     context: ./apis/autopay
  #     dockerfile: Dockerfile
  #   ports:
  #     - 9002:3000
  #   volumes:
  #     - ./apis/autopay:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: yarn start
  #   depends_on:
  #     - kafka
  #   restart: always

networks:
  default:
    driver: bridge